######################################

# This script defines the project pipeline - it specifys the execution orders for all the code in this
# repo using a series of actions.

######################################

version: '3.0'

expectations:
  population_size: 3000

actions:

  # Extract data ----
  # generate_study_population:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition --skip-existing --output-dir=output --output-format=csv.gz
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/input*.csv.gz

  generate_measure_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-09-01 to today by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input*.csv.gz

  calculate_measures:
    run: python:latest python analysis/calculate_measures.py
    needs: [generate_measure_population]
    outputs:
      highly_sensitive:
        measures: output/measures/measure_*.csv.gz
      moderately_sensitive:
        pivot_stats: output/measures/pivotstats_*.csv

  plot_measure_deciles:
    run: python:latest python analysis/plot_deciles.py
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        figures: output/figures/*.png
