######################################

# This script defines the project pipeline - it specifys the execution orders for all the code in this
# repo using a series of actions.

######################################

version: '3.0'

expectations:
  population_size: 1000000

actions:

  # Extract data ----
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --skip-existing --output-dir=output
    outputs:
      highly_sensitive:
        cohort: output/input*.csv

  generate_measure_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to today by month" --skip-existing --output-dir=output/measures
    outputs:
      highly_sensitive:
        cohort: output/measures/input*.csv

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
    needs: [generate_measure_population]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv

  plot_broad_spec_deciles:
    run: python:latest python analysis/plot_broad_spectrum_deciles.py
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        cohort: output/figures/broad_spectrum_decile_chart.png